---
title: "DeSHAPE_CaseStudy"
author: "Yiqian"
date: "2025-06-05"
output: html_document
---


# Loading functions
```{r}
library(phyloseq)
library(vegan)
library(ggplot2)
library(ggpubr)
library(car)
library(quantreg)
library(dplyr)
library(hillR)
library(devtools)
#devtools::install_github("bioscinema/DeSHAPE")
library(DeSHAPE)
```

# Cardiovascular_wgs

```{r}
load("../Real_Data/cardiovascular_wgs.RData")
meta <- as(sample_data(ps),"data.frame")
meta$SampleID <- rownames(meta)

meta <- meta %>%
  filter(grepl("^MMC", Status) | grepl("^HC", Status) | grepl("^IHD", Status)) %>%
  mutate(Status = ifelse(grepl("^MMC", Status), "MMC",
                         ifelse(grepl("^HC", Status), "HC", 
                                ifelse(grepl("^IHD", Status), "IHD", NA))))

meta <- meta %>%
  mutate(HbA1c = ifelse(HbA1c.... == "NA", NA, HbA1c....)) %>% 
  filter(!is.na(HbA1c)) %>%
  mutate(HbA1c = as.numeric(HbA1c....))

meta <- meta %>%
  filter(Gender %in% c("Female", "Male"))

ps_filt <- prune_samples(meta$SampleID, ps)
sample_data(ps_filt) <- sample_data(meta)
ps_filt <- prune_taxa(taxa_sums(ps_filt) > 0, ps_filt)

otu_mat <- as(otu_table(ps_filt), "matrix")
if (taxa_are_rows(ps_filt)) {
  otu_mat <- t(otu_mat)
}

depth <- rowSums(otu_mat)
```

## Shannon

```{r}
shannon_vec <- diversity(otu_mat, index = "shannon")
shannon_df <- data.frame(SampleID = rownames(otu_mat),
                         Shannon = shannon_vec)

meta_df <- as(sample_data(ps_filt),"data.frame")
meta_df$SampleID <- rownames(meta_df)

plot_df <- merge(shannon_df, meta_df, by = "SampleID")
plot_df$Depth <- depth


p1 <- ggplot(plot_df, aes(x = Status, y = Shannon, fill = Status)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.15, outlier.shape = NA) +
  stat_compare_means(method = "kruskal.test",
                     label.y  = max(plot_df$Shannon) * 1.05,
                     size     = 5.5,
                     fontface = "bold") +
  scale_fill_manual(values = c("HC"  = "#56B4E9",
                               "MMC" = "#E69F00",
                               "IHD" = "lightgreen")) +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = "Shannon Index") +
  theme(legend.position = "none",
        axis.title.y    = element_text(face = "bold", size = 18),
        axis.text       = element_text(face = "bold", size = 14),
        plot.title      = element_blank())

ggsave("card_shannon_violin.eps", plot = p1, device = cairo_ps, width = 6, height = 5)
p1

```

```{r}
pp = ggplot(plot_df, aes(x = Status, y = Shannon, fill = Status)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.15, outlier.shape = NA) +
  stat_deshape_compare(confounder_data = plot_df, confounder = c("Depth","Gender" ,"HbA1c"),
                     label.y  = max(plot_df$Shannon) * 0.93,label.x = 0.5,
                     size     = 6,
                     fontface = "bold") +
  scale_fill_manual(values = c("HC"  = "#56B4E9",
                               "MMC" = "#E69F00",
                               "IHD" = "lightgreen")) +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = "Shannon Index") +
  theme(legend.position = "none",
        axis.title.y    = element_text(face = "bold", size = 18),
        axis.text       = element_text(face = "bold", size = 14),
        plot.title      = element_blank())

ggsave("card_shannon_deshape.eps", plot = pp, device = cairo_ps, width = 6, height = 5)
```


```{r}
### Permutation-based test

### DeSHAPE 1: Median Diff Test
deshape_perm_multi(Shannon ~ Status,
               data        = plot_df,
               mode        = "center",     # or "dispersion", "skewness"
               perm        = 10000,
               seed = 2025)


### DeSHAPE 2: Dispersion Diff Test
deshape_perm_multi(Shannon ~ Status,
               data        = plot_df,
               mode        = "dispersion",     # or "dispersion", "skewness"
               perm        = 10000,
               seed = 2025)

### DeSHAPE 3: Asymmetry Test
deshape_perm_multi(Shannon ~ Status,
               data        = plot_df,
               mode        = "skewness",     # or "dispersion", "skewness"
               perm        = 10000,
               seed = 2025)
```


```{r}
#############################################################################
### Regression-based test

### DeSHAPE 1: Median Diff Test
fit_full <- rq(Shannon ~ Status, data = plot_df, tau = 0.5, method = "fn")
fit_null <- rq(Shannon ~ 1, data = plot_df, tau = 0.5, method = "fn")

anova(fit_null, fit_full, joint = TRUE)

# adjust sequencing depth
fit_full <- rq(Shannon ~ Status + Depth, data = plot_df, tau = 0.5, method = "fn")
fit_null <- rq(Shannon ~ Depth, data = plot_df, tau = 0.5, method = "fn")

anova(fit_null, fit_full, joint = TRUE)

# adjust sequencing depth and other confounders
fit_full <- rq(Shannon ~ Status + Depth + Gender + HbA1c, data = plot_df, tau = 0.5, method = "fn")
fit_null <- rq(Shannon ~ Depth + Gender + HbA1c, data = plot_df, tau = 0.5, method = "fn")

anova(fit_null, fit_full, joint = TRUE)

### DeSHAPE 2: Dispersion Diff Test
# H0: beta(2,0.75) - beta(2,0.25) = beta(3,0.75) - beta(3,0.25)
# H0: 0 - beta(2,0.25) + beta(3,0.25) + 0 + beta(2,0.75) - beta(3,0.75) = 0
# contrast vector C = (0,-1,1,0,1,-1)
deshape_wald_contrast(Shannon ~ Status,
                   data = plot_df,
                   taus = c(0.25,0.75),
                   contrast = c(0,-1,1,0,1,-1),
                   alternative = "two.sided",
                   kernel = "gaussian")

# adjust sequencing depth
deshape_wald_contrast(Shannon ~ Status + Depth,
                   data = plot_df,
                   taus = c(0.25,0.75),
                   contrast = c(0,-1,1,0,0,1,-1,0),
                   alternative = "two.sided",
                   kernel = "gaussian")

# adjust sequencing depth and other confounders
deshape_wald_contrast(Shannon ~ Status + Depth + Gender + HbA1c,
                   data = plot_df,
                   taus = c(0.25,0.75),
                   contrast = c(0,-1,1,0,0,0,0,1,-1,0,0,0),
                   alternative = "two.sided",
                   kernel = "gaussian")

### DeSHAPE 3: Asymmetry Test
# H0: beta(2,0.1) - 2*beta(2,0.5) + beta(2,0.9) = beta(3,0.1) - 2*beta(3,0.5) + beta(3,0.9)
# H0: 0 + beta(2,0.1) - beta(3,0.1) + 0 - 2*beta(2,0.5) + 2*beta(3,0.5) + 0 + beta(2,0.9) - beta(3,0.9) = 0
# contrast vector C = (0,1,-1,0,-2,2,0,1,-1)
deshape_wald_contrast(Shannon ~ Status,
                   data = plot_df,
                   taus = c(0.1,0.5,0.9),
                   contrast = c(0,1,-1,0,-2,2,0,1,-1),
                   alternative = "two.sided",
                   kernel = "gaussian")

# adjust sequencing depth
deshape_wald_contrast(Shannon ~ Status + Depth,
                   data = plot_df,
                   taus = c(0.1,0.5,0.9),
                   contrast = c(0,1,-1,0,0,-2,2,0,0,1,-1,0),
                   alternative = "two.sided",
                   kernel = "gaussian")

# adjust sequencing depth and other confounders
deshape_wald_contrast(Shannon ~ Status + Depth + Gender + HbA1c,
                   data = plot_df,
                   taus = c(0.1,0.5,0.9),
                   contrast = c(0,1,-1,0,0,0,0,-2,2,0,0,0,0,1,-1,0,0,0),
                   alternative = "two.sided",
                   kernel = "gaussian")


```

```{r}
deshape_glm_resid_test(Shannon ~ Status + Depth + Gender + HbA1c,
                       data = plot_df,
                       mode = "center",
                       family = Gamma(link = "log"), 
                       group = "Status",  # grouping variable name
                       alternative = "two.sided",
                       q = 0.25, B = 999, seed = 2025)$p.value

deshape_glm_resid_test(Shannon ~ Status + Depth + Gender + HbA1c,
                       data = plot_df,
                       mode = "dispersion",
                       family = Gamma(link = "log"), 
                       group = "Status",  # grouping variable name
                       alternative = "two.sided",
                       q = 0.25, B = 999, seed = 2025)$p.value

deshape_glm_resid_test(Shannon ~ Status + Depth + Gender + HbA1c,
                       data = plot_df,
                       mode = "skewness",
                       family = Gamma(link = "log"), 
                       group = "Status",  # grouping variable name
                       alternative = "two.sided",
                       q = 0.1, B = 999, seed = 2025)$p.value
```


## Faith's PD

```{r}
tree = phy_tree(ps_filt)
shannon_vec <- setNames(picante::pd(otu_mat, tree, include.root = TRUE)$PD, rownames(otu_mat))
shannon_df <- data.frame(SampleID = rownames(otu_mat),
                         Shannon = shannon_vec)

meta_df <- as(sample_data(ps_filt),"data.frame")
meta_df$SampleID <- rownames(meta_df)

plot_df <- merge(shannon_df, meta_df, by = "SampleID")
plot_df$Depth <- depth

p2 <- ggplot(plot_df, aes(x = Status, y = Shannon, fill = Status)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.15, outlier.shape = NA) +
  stat_compare_means(method = "kruskal.test",
                     label.y  = max(plot_df$Shannon) * 1.05,
                     size     = 5.5,
                     fontface = "bold") +
  scale_fill_manual(values = c("HC"  = "#56B4E9",
                               "MMC" = "#E69F00",
                               "IHD" = "lightgreen")) +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = "Faith's PD Index") +
  theme(legend.position = "none",
        axis.title.y    = element_text(face = "bold", size = 18),
        axis.text       = element_text(face = "bold", size = 14),
        plot.title      = element_blank())

ggsave("card_FaithPD_violin.eps", plot = p2, device = cairo_ps, width = 6, height = 5)
p2
```

```{r}
pp = ggplot(plot_df, aes(x = Status, y = Shannon, fill = Status)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.15, outlier.shape = NA) +
  stat_deshape_compare(confounder_data = plot_df, confounder = c("Depth","Gender" ,"HbA1c"),
                     label.y  = max(plot_df$Shannon) * 0.87,label.x = 0.5,
                     size     = 6,
                     fontface = "bold") +
  scale_fill_manual(values = c("HC"  = "#56B4E9",
                               "MMC" = "#E69F00",
                               "IHD" = "lightgreen")) +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = "Faith's PD Index") +
  theme(legend.position = "none",
        axis.title.y    = element_text(face = "bold", size = 18),
        axis.text       = element_text(face = "bold", size = 14),
        plot.title      = element_blank())

ggsave("card_faithPD_deshape.eps", plot = pp, device = cairo_ps, width = 6, height = 5)
```


```{r}
### Permutation-based test

### DeSHAPE 1: Median Diff Test
deshape_perm_multi(Shannon ~ Status,
               data        = plot_df,
               mode        = "center",     # or "dispersion", "skewness"
               perm        = 10000,
               seed = 2025)


### DeSHAPE 2: Dispersion Diff Test
deshape_perm_multi(Shannon ~ Status,
               data        = plot_df,
               mode        = "dispersion",     # or "dispersion", "skewness"
               perm        = 10000,
               seed = 2025)

### DeSHAPE 3: Asymmetry Test
deshape_perm_multi(Shannon ~ Status,
               data        = plot_df,
               mode        = "skewness",     # or "dispersion", "skewness"
               perm        = 10000,
               seed = 2025)
```

```{r}
#############################################################################
### Regression-based test

### DeSHAPE 1: Median Diff Test
fit_full <- rq(Shannon ~ Status, data = plot_df, tau = 0.5, method = "fn")
fit_null <- rq(Shannon ~ 1, data = plot_df, tau = 0.5, method = "fn")

anova(fit_null, fit_full, joint = TRUE)

# adjust sequencing depth
fit_full <- rq(Shannon ~ Status + Depth, data = plot_df, tau = 0.5, method = "fn")
fit_null <- rq(Shannon ~ Depth, data = plot_df, tau = 0.5, method = "fn")

anova(fit_null, fit_full, joint = TRUE)

# adjust sequencing depth and other confounders
fit_full <- rq(Shannon ~ Status + Depth + Gender + HbA1c, data = plot_df, tau = 0.5, method = "fn")
fit_null <- rq(Shannon ~ Depth + Gender + HbA1c, data = plot_df, tau = 0.5, method = "fn")

anova(fit_null, fit_full, joint = TRUE)

### DeSHAPE 2: Dispersion Diff Test
# H0: beta(2,0.75) - beta(2,0.25) = beta(3,0.75) - beta(3,0.25)
# H0: 0 - beta(2,0.25) + beta(3,0.25) + 0 + beta(2,0.75) - beta(3,0.75) = 0
# contrast vector C = (0,-1,1,0,1,-1)
deshape_wald_contrast(Shannon ~ Status,
                   data = plot_df,
                   taus = c(0.25,0.75),
                   contrast = c(0,-1,1,0,1,-1),
                   alternative = "two.sided",
                   kernel = "gaussian")

# adjust sequencing depth
deshape_wald_contrast(Shannon ~ Status + Depth,
                   data = plot_df,
                   taus = c(0.25,0.75),
                   contrast = c(0,-1,1,0,0,1,-1,0),
                   alternative = "two.sided",
                   kernel = "gaussian")

# adjust sequencing depth and other confounders
deshape_wald_contrast(Shannon ~ Status + Depth + Gender + HbA1c,
                   data = plot_df,
                   taus = c(0.25,0.75),
                   contrast = c(0,-1,1,0,0,0,0,1,-1,0,0,0),
                   alternative = "two.sided",
                   kernel = "gaussian")

### DeSHAPE 3: Asymmetry Test
# H0: beta(2,0.1) - 2*beta(2,0.5) + beta(2,0.9) = beta(3,0.1) - 2*beta(3,0.5) + beta(3,0.9)
# H0: 0 + beta(2,0.1) - beta(3,0.1) + 0 - 2*beta(2,0.5) + 2*beta(3,0.5) + 0 + beta(2,0.9) - beta(3,0.9) = 0
# contrast vector C = (0,1,-1,0,-2,2,0,1,-1)
deshape_wald_contrast(Shannon ~ Status,
                   data = plot_df,
                   taus = c(0.1,0.5,0.9),
                   contrast = c(0,1,-1,0,-2,2,0,1,-1),
                   alternative = "two.sided",
                   kernel = "gaussian")

# adjust sequencing depth
deshape_wald_contrast(Shannon ~ Status + Depth,
                   data = plot_df,
                   taus = c(0.1,0.5,0.9),
                   contrast = c(0,1,-1,0,0,-2,2,0,0,1,-1,0),
                   alternative = "two.sided",
                   kernel = "gaussian")

# adjust sequencing depth and other confounders
deshape_wald_contrast(Shannon ~ Status + Depth + Gender + HbA1c,
                   data = plot_df,
                   taus = c(0.1,0.5,0.9),
                   contrast = c(0,1,-1,0,0,0,0,-2,2,0,0,0,0,1,-1,0,0,0),
                   alternative = "two.sided",
                   kernel = "gaussian")

```

```{r}
deshape_glm_resid_test(Shannon ~ Status + Depth + Gender + HbA1c,
                       data = plot_df,
                       mode = "center",
                       family = Gamma(link = "log"), 
                       group = "Status",  # grouping variable name
                       alternative = "two.sided",
                       q = 0.25, B = 999, seed = 2025)$p.value

deshape_glm_resid_test(Shannon ~ Status + Depth + Gender + HbA1c,
                       data = plot_df,
                       mode = "dispersion",
                       family = Gamma(link = "log"), 
                       group = "Status",  # grouping variable name
                       alternative = "two.sided",
                       q = 0.25, B = 999, seed = 2025)$p.value

deshape_glm_resid_test(Shannon ~ Status + Depth + Gender + HbA1c,
                       data = plot_df,
                       mode = "skewness",
                       family = Gamma(link = "log"), 
                       group = "Status",  # grouping variable name
                       alternative = "two.sided",
                       q = 0.1, B = 999, seed = 2025)$p.value
```

## Chao1

```{r}
shannon_vec <- setNames(apply(otu_mat, 1, function(x) vegan::estimateR(x)["S.chao1"]), rownames(otu_mat))

shannon_df <- data.frame(SampleID = rownames(otu_mat),
                         Shannon = shannon_vec)

meta_df <- as(sample_data(ps_filt),"data.frame")
meta_df$SampleID <- rownames(meta_df)

plot_df <- merge(shannon_df, meta_df, by = "SampleID")
plot_df$Depth <- depth

p3 <- ggplot(plot_df, aes(x = Status, y = Shannon, fill = Status)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.15, outlier.shape = NA) +
  stat_compare_means(method = "kruskal.test",
                     label.y  = max(plot_df$Shannon) * 1.05,
                     size     = 5.5,
                     fontface = "bold") +
  scale_fill_manual(values = c("HC"  = "#56B4E9",
                               "MMC" = "#E69F00",
                               "IHD" = "lightgreen")) +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = "Chao1 Index") +
  theme(legend.position = "none",
        axis.title.y    = element_text(face = "bold", size = 18),
        axis.text       = element_text(face = "bold", size = 14),
        plot.title      = element_blank())

ggsave("card_Chao1_violin.eps", plot = p3, device = cairo_ps, width = 6, height = 5)
p3
```

```{r}
pp = ggplot(plot_df, aes(x = Status, y = Shannon, fill = Status)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.15, outlier.shape = NA) +
  stat_deshape_compare(confounder_data = plot_df, confounder = c("Depth","Gender" ,"HbA1c"),
                     label.y  = max(plot_df$Shannon) * 0.87,
                     label.x = 0.5,
                     size     = 6,
                     fontface = "bold") +
  scale_fill_manual(values = c("HC"  = "#56B4E9",
                               "MMC" = "#E69F00",
                               "IHD" = "lightgreen")) +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = "Chao1 Index") +
  theme(legend.position = "none",
        axis.title.y    = element_text(face = "bold", size = 18),
        axis.text       = element_text(face = "bold", size = 14),
        plot.title      = element_blank())

ggsave("card_Chao1_deshape.eps", plot = pp, device = cairo_ps, width = 6, height = 5)
```


```{r}
### Permutation-based test

### DeSHAPE 1: Median Diff Test
deshape_perm_multi(Shannon ~ Status,
               data        = plot_df,
               mode        = "center",     # or "dispersion", "skewness"
               perm        = 10000,
               seed = 2025)


### DeSHAPE 2: Dispersion Diff Test
deshape_perm_multi(Shannon ~ Status,
               data        = plot_df,
               mode        = "dispersion",     # or "dispersion", "skewness"
               perm        = 10000,
               seed = 2025)

### DeSHAPE 3: Asymmetry Test
deshape_perm_multi(Shannon ~ Status,
               data        = plot_df,
               mode        = "skewness",     # or "dispersion", "skewness"
               perm        = 10000,
               seed = 2025)
```

```{r}
#############################################################################
### Regression-based test

### DeSHAPE 1: Median Diff Test
fit_full <- rq(Shannon ~ Status, data = plot_df, tau = 0.5, method = "fn")
fit_null <- rq(Shannon ~ 1, data = plot_df, tau = 0.5, method = "fn")

anova(fit_null, fit_full, joint = TRUE)

# adjust sequencing depth
fit_full <- rq(Shannon ~ Status + Depth, data = plot_df, tau = 0.5, method = "fn")
fit_null <- rq(Shannon ~ Depth, data = plot_df, tau = 0.5, method = "fn")

anova(fit_null, fit_full, joint = TRUE)

# adjust sequencing depth and other confounders
fit_full <- rq(Shannon ~ Status + Depth + Gender + HbA1c, data = plot_df, tau = 0.5, method = "fn")
fit_null <- rq(Shannon ~ Depth + Gender + HbA1c, data = plot_df, tau = 0.5, method = "fn")

anova(fit_null, fit_full, joint = TRUE)

### DeSHAPE 2: Dispersion Diff Test
# H0: beta(2,0.75) - beta(2,0.25) = beta(3,0.75) - beta(3,0.25)
# H0: 0 - beta(2,0.25) + beta(3,0.25) + 0 + beta(2,0.75) - beta(3,0.75) = 0
# contrast vector C = (0,-1,1,0,1,-1)
deshape_wald_contrast(Shannon ~ Status,
                   data = plot_df,
                   taus = c(0.25,0.75),
                   contrast = c(0,-1,1,0,1,-1),
                   alternative = "two.sided",
                   kernel = "gaussian")

# adjust sequencing depth
deshape_wald_contrast(Shannon ~ Status + Depth,
                   data = plot_df,
                   taus = c(0.25,0.75),
                   contrast = c(0,-1,1,0,0,1,-1,0),
                   alternative = "two.sided",
                   kernel = "gaussian")

# adjust sequencing depth and other confounders
deshape_wald_contrast(Shannon ~ Status + Depth + Gender + HbA1c,
                   data = plot_df,
                   taus = c(0.25,0.75),
                   contrast = c(0,-1,1,0,0,0,0,1,-1,0,0,0),
                   alternative = "two.sided",
                   kernel = "gaussian")

### DeSHAPE 3: Asymmetry Test
# H0: beta(2,0.1) - 2*beta(2,0.5) + beta(2,0.9) = beta(3,0.1) - 2*beta(3,0.5) + beta(3,0.9)
# H0: 0 + beta(2,0.1) - beta(3,0.1) + 0 - 2*beta(2,0.5) + 2*beta(3,0.5) + 0 + beta(2,0.9) - beta(3,0.9) = 0
# contrast vector C = (0,1,-1,0,-2,2,0,1,-1)
deshape_wald_contrast(Shannon ~ Status,
                   data = plot_df,
                   taus = c(0.1,0.5,0.9),
                   contrast = c(0,1,-1,0,-2,2,0,1,-1),
                   alternative = "two.sided",
                   kernel = "gaussian")

# adjust sequencing depth
deshape_wald_contrast(Shannon ~ Status + Depth,
                   data = plot_df,
                   taus = c(0.1,0.5,0.9),
                   contrast = c(0,1,-1,0,0,-2,2,0,0,1,-1,0),
                   alternative = "two.sided",
                   kernel = "gaussian")

# adjust sequencing depth and other confounders
deshape_wald_contrast(Shannon ~ Status + Depth + Gender + HbA1c,
                   data = plot_df,
                   taus = c(0.1,0.5,0.9),
                   contrast = c(0,1,-1,0,0,0,0,-2,2,0,0,0,0,1,-1,0,0,0),
                   alternative = "two.sided",
                   kernel = "gaussian")

```

```{r}
deshape_glm_resid_test(Shannon ~ Status + Depth + Gender + HbA1c,
                       data = plot_df,
                       mode = "center",
                       family = Gamma(link = "log"), 
                       group = "Status",  # grouping variable name
                       alternative = "two.sided",
                       q = 0.25, B = 999, seed = 2025)$p.value

deshape_glm_resid_test(Shannon ~ Status + Depth + Gender + HbA1c,
                       data = plot_df,
                       mode = "dispersion",
                       family = Gamma(link = "log"), 
                       group = "Status",  # grouping variable name
                       alternative = "two.sided",
                       q = 0.25, B = 999, seed = 2025)$p.value

deshape_glm_resid_test(Shannon ~ Status + Depth + Gender + HbA1c,
                       data = plot_df,
                       mode = "skewness",
                       family = Gamma(link = "log"), 
                       group = "Status",  # grouping variable name
                       alternative = "two.sided",
                       q = 0.1, B = 999, seed = 2025)$p.value
```

## q-PD (q=1)

```{r}
tree = phy_tree(ps_filt)
shannon_vec <-  hill_phylo(comm = otu_mat, tree = tree, q = 1, rel_then_pool = FALSE)

# Assign sample names
names(shannon_vec) <- rownames(otu_mat)
shannon_df <- data.frame(SampleID = rownames(otu_mat),
                         Shannon = shannon_vec)

meta_df <- as(sample_data(ps_filt),"data.frame")
meta_df$SampleID <- rownames(meta_df)

plot_df <- merge(shannon_df, meta_df, by = "SampleID")
plot_df$Depth <- depth

p4 <- ggplot(plot_df, aes(x = Status, y = Shannon, fill = Status)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.15, outlier.shape = NA) +
  stat_compare_means(method = "kruskal.test",
                     label.y  = max(plot_df$Shannon) * 1.05,
                     size     = 5.5,
                     fontface = "bold") +
  scale_fill_manual(values = c("HC"  = "#56B4E9",
                               "MMC" = "#E69F00",
                               "IHD" = "lightgreen")) +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = "q-PD (q=1) Index") +
  theme(legend.position = "none",
        axis.title.y    = element_text(face = "bold", size = 18),
        axis.text       = element_text(face = "bold", size = 14),
        plot.title      = element_blank())

ggsave("card_qPD_violin.eps", plot = p4, device = cairo_ps, width = 6, height = 5)
p4
```

```{r}
pp = ggplot(plot_df, aes(x = Status, y = Shannon, fill = Status)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.15, outlier.shape = NA) +
  stat_deshape_compare(confounder_data = plot_df, confounder = c("Depth","Gender" ,"HbA1c"),
                     label.y  = max(plot_df$Shannon) * 0.93,label.x = 0.5,
                     size     = 6,
                     fontface = "bold") +
  scale_fill_manual(values = c("HC"  = "#56B4E9",
                               "MMC" = "#E69F00",
                               "IHD" = "lightgreen")) +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = "q-PD (q=1) Index") +
  theme(legend.position = "none",
        axis.title.y    = element_text(face = "bold", size = 18),
        axis.text       = element_text(face = "bold", size = 14),
        plot.title      = element_blank())

ggsave("card_qPD_deshape.eps", plot = pp, device = cairo_ps, width = 6, height = 5)
```

```{r}
library(cowplot)
library(magick)
library(ggplot2)
grid <- plot_grid(p1, p2, p3, p4, ncol = 2, align = "hv")
ggsave("Card_combined_2x2.eps", grid, device = cairo_ps, width = 8, height = 8, units = "in")
```


```{r}
### Permutation-based test

### DeSHAPE 1: Median Diff Test
deshape_perm_multi(Shannon ~ Status,
               data        = plot_df,
               mode        = "center",     # or "dispersion", "skewness"
               perm        = 10000,
               seed = 2025)


### DeSHAPE 2: Dispersion Diff Test
deshape_perm_multi(Shannon ~ Status,
               data        = plot_df,
               mode        = "dispersion",     # or "dispersion", "skewness"
               perm        = 10000,
               seed = 2025)

### DeSHAPE 3: Asymmetry Test
deshape_perm_multi(Shannon ~ Status,
               data        = plot_df,
               mode        = "skewness",     # or "dispersion", "skewness"
               perm        = 10000,
               seed = 2025)
```

```{r}
#############################################################################
### Regression-based test

### DeSHAPE 1: Median Diff Test
fit_full <- rq(Shannon ~ Status, data = plot_df, tau = 0.5, method = "fn")
fit_null <- rq(Shannon ~ 1, data = plot_df, tau = 0.5, method = "fn")

anova(fit_null, fit_full, joint = TRUE)

# adjust sequencing depth
fit_full <- rq(Shannon ~ Status + Depth, data = plot_df, tau = 0.5, method = "fn")
fit_null <- rq(Shannon ~ Depth, data = plot_df, tau = 0.5, method = "fn")

anova(fit_null, fit_full, joint = TRUE)

# adjust sequencing depth and other confounders
fit_full <- rq(Shannon ~ Status + Depth + Gender + HbA1c, data = plot_df, tau = 0.5, method = "fn")
fit_null <- rq(Shannon ~ Depth + Gender + HbA1c, data = plot_df, tau = 0.5, method = "fn")

anova(fit_null, fit_full, joint = TRUE)

### DeSHAPE 2: Dispersion Diff Test
# H0: beta(2,0.75) - beta(2,0.25) = beta(3,0.75) - beta(3,0.25)
# H0: 0 - beta(2,0.25) + beta(3,0.25) + 0 + beta(2,0.75) - beta(3,0.75) = 0
# contrast vector C = (0,-1,1,0,1,-1)
deshape_wald_contrast(Shannon ~ Status,
                   data = plot_df,
                   taus = c(0.25,0.75),
                   contrast = c(0,-1,1,0,1,-1),
                   alternative = "two.sided",
                   kernel = "gaussian")

# adjust sequencing depth
deshape_wald_contrast(Shannon ~ Status + Depth,
                   data = plot_df,
                   taus = c(0.25,0.75),
                   contrast = c(0,-1,1,0,0,1,-1,0),
                   alternative = "two.sided",
                   kernel = "gaussian")

# adjust sequencing depth and other confounders
deshape_wald_contrast(Shannon ~ Status + Depth + Gender + HbA1c,
                   data = plot_df,
                   taus = c(0.25,0.75),
                   contrast = c(0,-1,1,0,0,0,0,1,-1,0,0,0),
                   alternative = "two.sided",
                   kernel = "gaussian")

### DeSHAPE 3: Asymmetry Test
# H0: beta(2,0.1) - 2*beta(2,0.5) + beta(2,0.9) = beta(3,0.1) - 2*beta(3,0.5) + beta(3,0.9)
# H0: 0 + beta(2,0.1) - beta(3,0.1) + 0 - 2*beta(2,0.5) + 2*beta(3,0.5) + 0 + beta(2,0.9) - beta(3,0.9) = 0
# contrast vector C = (0,1,-1,0,-2,2,0,1,-1)
deshape_wald_contrast(Shannon ~ Status,
                   data = plot_df,
                   taus = c(0.1,0.5,0.9),
                   contrast = c(0,1,-1,0,-2,2,0,1,-1),
                   alternative = "two.sided",
                   kernel = "gaussian")

# adjust sequencing depth
deshape_wald_contrast(Shannon ~ Status + Depth,
                   data = plot_df,
                   taus = c(0.1,0.5,0.9),
                   contrast = c(0,1,-1,0,0,-2,2,0,0,1,-1,0),
                   alternative = "two.sided",
                   kernel = "gaussian")

# adjust sequencing depth and other confounders
deshape_wald_contrast(Shannon ~ Status + Depth + Gender + HbA1c,
                   data = plot_df,
                   taus = c(0.1,0.5,0.9),
                   contrast = c(0,1,-1,0,0,0,0,-2,2,0,0,0,0,1,-1,0,0,0),
                   alternative = "two.sided",
                   kernel = "gaussian")

```

```{r}
deshape_glm_resid_test(Shannon ~ Status + Depth + Gender + HbA1c,
                       data = plot_df,
                       mode = "center",
                       family = Gamma(link = "log"), 
                       group = "Status",  # grouping variable name
                       alternative = "two.sided",
                       q = 0.25, B = 999, seed = 2025)$p.value

deshape_glm_resid_test(Shannon ~ Status + Depth + Gender + HbA1c,
                       data = plot_df,
                       mode = "dispersion",
                       family = Gamma(link = "log"), 
                       group = "Status",  # grouping variable name
                       alternative = "two.sided",
                       q = 0.25, B = 999, seed = 2025)$p.value

deshape_glm_resid_test(Shannon ~ Status + Depth + Gender + HbA1c,
                       data = plot_df,
                       mode = "skewness",
                       family = Gamma(link = "log"), 
                       group = "Status",  # grouping variable name
                       alternative = "two.sided",
                       q = 0.1, B = 999, seed = 2025)$p.value
```

# Tumour-microbiome

```{r}
load("../Real_Data/tumor_rooted.RData")
phy_16S <- physeq.tree
sample_data(physeq.tree)$group_prefix <- substr(sample_data(physeq.tree)$group, 1, 3)

phy_16S <- subset_samples(physeq.tree, group_prefix != "C")

phy_16S <- prune_taxa(taxa_sums(phy_16S) > 0, phy_16S)

sample_data(phy_16S)$group_prefix <- factor(sample_data(phy_16S)$group_prefix)
sample_data(phy_16S)$Cohort <- factor(sample_data(phy_16S)$Cohort)
otu_mat <- as(otu_table(phy_16S ), "matrix")
if (taxa_are_rows(phy_16S )) {
  otu_mat <- t(otu_mat)
}
depth <- rowSums(otu_mat)
```


## Shannon

```{r}
shannon_vec <- diversity(otu_mat, index = "shannon")
shannon_df <- data.frame(SampleID = rownames(otu_mat),
                         Shannon = shannon_vec)

meta_df <- as(sample_data(phy_16S),"data.frame")
meta_df$SampleID <- rownames(meta_df)

plot_df <- merge(shannon_df, meta_df, by = "SampleID")
plot_df$Depth <- depth

p1 <- ggplot(plot_df, aes(x = group_prefix, y = Shannon, fill = group_prefix)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.15, outlier.shape = NA) +
  stat_compare_means(
    method = "wilcox.test",
    label.y = max(plot_df$Shannon) * 1.05,
    size = 6,
    fontface = "bold"
  ) +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = "Shannon Index") +
  scale_fill_manual(values = c("LTS" = "#E69F00", "STS" = "#56B4E9")) +
  theme(
    legend.position = "none",
    axis.title.y = element_text(face = "bold", size = 18),
    axis.text = element_text(face = "bold", size = 14),
    axis.title.x = element_blank(),
    plot.title = element_blank()
  )

ggsave("tumer_shannon_violin.eps", plot = p1, device = cairo_ps, width = 6, height = 5)
p1
```

```{r}
pp = ggplot(plot_df, aes(x = group_prefix, y = Shannon, fill = group_prefix)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.15, outlier.shape = NA) +
  stat_deshape_compare(
    confounder_data = plot_df,
    confounder = c("Cohort", "Depth"),
    alternative = "greater",
    label.y = max(plot_df$Shannon) * 0.98,label.x = 0.5,
    size = 6,
    fontface = "bold"
  ) +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = "Shannon Index") +
  scale_fill_manual(values = c("LTS" = "#E69F00", "STS" = "#56B4E9")) +
  theme(
    legend.position = "none",
    axis.title.y = element_text(face = "bold", size = 18),
    axis.text = element_text(face = "bold", size = 14),
    axis.title.x = element_blank(),
    plot.title = element_blank()
  )

ggsave("Tumour_Shannon_deshape.eps", plot = pp, device = cairo_ps, width = 6, height = 5)
```

```{r}
### Permutation-based test

### DeSHAPE 1: Median Diff Test
deshape_perm_pair(Shannon ~ group_prefix,
               data        = plot_df,
               mode        = "center",     # or "dispersion", "skewness
               alternative = "greater",
               perm        = 10000,
               seed = 2025)


### DeSHAPE 2: Dispersion Diff Test
deshape_perm_pair(Shannon ~ group_prefix,
               data        = plot_df,
               mode        = "dispersion",     # or "dispersion", "skewness"
               alternative = "greater",
               perm        = 10000,
               seed = 2025)

### DeSHAPE 3: Asymmetry Test
deshape_perm_pair(Shannon ~ group_prefix,
               data        = plot_df,
               mode        = "skewness",     # or "dispersion", "skewness"
               alternative = "greater",
               perm        = 10000,
               seed = 2025)

```

```{r}
### DeSHAPE 1: Median Diff via Quantile Reg
qr_fit <- rq(Shannon ~ group_prefix,
             data = plot_df,
             tau = 0.5,
             method = "fn")

set.seed(2025)
summary(qr_fit, se = "boot") 

# adjust sequencing depth
qr_fit_d <- rq(Shannon ~ group_prefix + Depth,
               data = plot_df,
               tau = 0.5,
               method = "fn")

set.seed(2025)
summary(qr_fit_d, se = "boot") 

# adjust sequencing depth and other confounders
qr_fit_d_c <- rq(Shannon ~ group_prefix + Cohort + Depth,
               data = plot_df,
               tau = 0.5,
               method = "fn")

set.seed(2025)
summary(qr_fit_d_c, se = "boot") 

### DeSHAPE 2: Dispersion Diff via Quantile Reg
deshape_wald_contrast(Shannon ~ group_prefix,
                   data = plot_df,
                   taus = c(0.25,0.75),
                   contrast = c(0,-1,0,1),
                   alternative = "greater",
                   kernel = "gaussian")

# adjust sequencing depth
deshape_wald_contrast(Shannon ~ group_prefix + Depth,
                   data = plot_df,
                   taus = c(0.25,0.75),
                   contrast = c(0,-1,0,0,1,0),
                   alternative = "greater",
                   kernel = "gaussian")

# adjust sequencing depth and other confounders
deshape_wald_contrast(Shannon ~ group_prefix + Cohort + Depth,
                   data = plot_df,
                   taus = c(0.25,0.75),
                   contrast = c(0,-1,0,0,0,1,0,0),
                   alternative = "greater",
                   kernel = "gaussian")

### DeSHAPE 3: Asymmetry Diff via Quantile Reg
deshape_wald_contrast(Shannon ~ group_prefix,
                   data = plot_df,
                   taus = c(0.1,0.5,0.9),
                   contrast = c(0,1,0,-2,0,1),
                   alternative = "greater",
                   kernel = "gaussian")

# adjust sequencing depth
deshape_wald_contrast(Shannon ~ group_prefix + Depth,
                   data = plot_df,
                   taus = c(0.1,0.5,0.9),
                   contrast = c(0,1,0,0,-2,0,0,1,0),
                   alternative = "greater",
                   kernel = "gaussian")

# adjust sequencing depth and other confounders
deshape_wald_contrast(Shannon ~ group_prefix + Cohort + Depth,
                   data = plot_df,
                   taus = c(0.1,0.5,0.9),
                   contrast = c(0,1,0,0,0,-2,0,0,0,1,0,0),
                   alternative = "greater",
                   kernel = "gaussian")

```

```{r}
deshape_glm_resid_test(Shannon ~ group_prefix + Cohort + Depth,
                       data = plot_df,
                       mode = "center",
                       family = Gamma(link = "log"), 
                       group = "group_prefix",  # grouping variable name
                       alternative = "greater",
                       q = 0.25, B = 999, seed = 2025)$p.value

deshape_glm_resid_test(Shannon ~ group_prefix + Cohort + Depth,
                       data = plot_df,
                       mode = "dispersion",
                       family = Gamma(link = "log"), 
                       group = "group_prefix",  # grouping variable name
                       alternative = "greater",
                       q = 0.25, B = 999, seed = 2025)$p.value

deshape_glm_resid_test(Shannon ~ group_prefix + Cohort + Depth,
                       data = plot_df,
                       mode = "skewness",
                       family = Gamma(link = "log"), 
                       group = "group_prefix",  # grouping variable name
                       alternative = "greater",
                       q = 0.1, B = 999, seed = 2025)$p.value
```

## Faith's PD

```{r}
tree = phy_tree(phy_16S)
shannon_vec <- setNames(picante::pd(otu_mat, tree, include.root = TRUE)$PD, rownames(otu_mat))
shannon_df <- data.frame(SampleID = rownames(otu_mat),
                         Shannon = shannon_vec)

meta_df <- as(sample_data(phy_16S),"data.frame")
meta_df$SampleID <- rownames(meta_df)

plot_df <- merge(shannon_df, meta_df, by = "SampleID")
plot_df$Depth <- depth

p2 <- ggplot(plot_df, aes(x = group_prefix, y = Shannon, fill = group_prefix)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.15, outlier.shape = NA) +
  stat_compare_means(
    method = "wilcox.test",
    label.y = max(plot_df$Shannon) * 1.05,
    size = 6,
    fontface = "bold"
  ) +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = "Faith's Index") +
  scale_fill_manual(values = c("LTS" = "#E69F00", "STS" = "#56B4E9")) +
  theme(
    legend.position = "none",
    axis.title.y = element_text(face = "bold", size = 18),
    axis.text = element_text(face = "bold", size = 14),
    axis.title.x = element_blank(),
    plot.title = element_blank()
  )

ggsave("tumer_FaithsPD_violin.eps", plot = p2, device = cairo_ps, width = 6, height = 5)
p2
```

```{r}
pp = ggplot(plot_df, aes(x = group_prefix, y = Shannon, fill = group_prefix)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.15, outlier.shape = NA) +
  stat_deshape_compare(
    confounder_data = plot_df,
    confounder = c("Cohort", "Depth"),
    alternative = "greater",
    label.y = max(plot_df$Shannon) * 0.94,label.x = 0.5,
    size = 6,
    fontface = "bold"
  ) +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = "Faith's Index") +
  scale_fill_manual(values = c("LTS" = "#E69F00", "STS" = "#56B4E9")) +
  theme(
    legend.position = "none",
    axis.title.y = element_text(face = "bold", size = 18),
    axis.text = element_text(face = "bold", size = 14),
    axis.title.x = element_blank(),
    plot.title = element_blank()
  )

ggsave("Tumour_Faith_deshape.eps", plot = pp, device = cairo_ps, width = 6, height = 5)
```

```{r}
### Permutation-based test

### DeSHAPE 1: Median Diff Test
deshape_perm_pair(Shannon ~ group_prefix,
               data        = plot_df,
               mode        = "center",     # or "dispersion", "skewness
               alternative = "greater",
               perm        = 10000,
               seed = 2025)


### DeSHAPE 2: Dispersion Diff Test
deshape_perm_pair(Shannon ~ group_prefix,
               data        = plot_df,
               mode        = "dispersion",     # or "dispersion", "skewness"
               alternative = "greater",
               perm        = 10000,
               seed = 2025)

### DeSHAPE 3: Asymmetry Test
deshape_perm_pair(Shannon ~ group_prefix,
               data        = plot_df,
               mode        = "skewness",     # or "dispersion", "skewness"
               alternative = "greater",
               perm        = 10000,
               seed = 2025)
```

```{r}
### DeSHAPE 1: Median Diff via Quantile Reg
qr_fit <- rq(Shannon ~ group_prefix,
             data = plot_df,
             tau = 0.5,
             method = "fn")

set.seed(2025)
summary(qr_fit, se = "boot") 

# adjust sequencing depth
qr_fit_d <- rq(Shannon ~ group_prefix + Depth,
               data = plot_df,
               tau = 0.5,
               method = "fn")

set.seed(2025)
summary(qr_fit_d, se = "boot") 

# adjust sequencing depth and other confounders
qr_fit_d_c <- rq(Shannon ~ group_prefix + Cohort + Depth,
               data = plot_df,
               tau = 0.5,
               method = "fn")

set.seed(2025)
summary(qr_fit_d_c, se = "boot") 

### DeSHAPE 2: Dispersion Diff via Quantile Reg
deshape_wald_contrast(Shannon ~ group_prefix,
                   data = plot_df,
                   taus = c(0.25,0.75),
                   contrast = c(0,-1,0,1),
                   alternative = "greater",
                   kernel = "gaussian")

# adjust sequencing depth
deshape_wald_contrast(Shannon ~ group_prefix + Depth,
                   data = plot_df,
                   taus = c(0.25,0.75),
                   contrast = c(0,-1,0,0,1,0),
                   alternative = "greater",
                   kernel = "gaussian")

# adjust sequencing depth and other confounders
deshape_wald_contrast(Shannon ~ group_prefix + Cohort + Depth,
                   data = plot_df,
                   taus = c(0.25,0.75),
                   contrast = c(0,-1,0,0,0,1,0,0),
                   alternative = "greater",
                   kernel = "gaussian")

### DeSHAPE 3: Asymmetry Diff via Quantile Reg
deshape_wald_contrast(Shannon ~ group_prefix,
                   data = plot_df,
                   taus = c(0.1,0.5,0.9),
                   contrast = c(0,1,0,-2,0,1),
                   alternative = "greater",
                   kernel = "gaussian")

# adjust sequencing depth
deshape_wald_contrast(Shannon ~ group_prefix + Depth,
                   data = plot_df,
                   taus = c(0.1,0.5,0.9),
                   contrast = c(0,1,0,0,-2,0,0,1,0),
                   alternative = "greater",
                   kernel = "gaussian")

# adjust sequencing depth and other confounders
deshape_wald_contrast(Shannon ~ group_prefix + Cohort + Depth,
                   data = plot_df,
                   taus = c(0.1,0.5,0.9),
                   contrast = c(0,1,0,0,0,-2,0,0,0,1,0,0),
                   alternative = "greater",
                   kernel = "gaussian")

```

```{r}
deshape_glm_resid_test(Shannon ~ group_prefix + Cohort + Depth,
                       data = plot_df,
                       mode = "center",
                       family = Gamma(link = "log"), 
                       group = "group_prefix",  # grouping variable name
                       alternative = "greater",
                       q = 0.25, B = 999, seed = 2025)$p.value

deshape_glm_resid_test(Shannon ~ group_prefix + Cohort + Depth,
                       data = plot_df,
                       mode = "dispersion",
                       family = Gamma(link = "log"), 
                       group = "group_prefix",  # grouping variable name
                       alternative = "greater",
                       q = 0.25, B = 999, seed = 2025)$p.value

deshape_glm_resid_test(Shannon ~ group_prefix + Cohort + Depth,
                       data = plot_df,
                       mode = "skewness",
                       family = Gamma(link = "log"), 
                       group = "group_prefix",  # grouping variable name
                       alternative = "greater",
                       q = 0.1, B = 999, seed = 2025)$p.value
```

## Chao1

```{r}
shannon_vec <- setNames(apply(otu_mat, 1, function(x) vegan::estimateR(x)["S.chao1"]), rownames(otu_mat))
shannon_df <- data.frame(SampleID = rownames(otu_mat),
                         Shannon = shannon_vec)

meta_df <- as(sample_data(phy_16S),"data.frame")
meta_df$SampleID <- rownames(meta_df)

plot_df <- merge(shannon_df, meta_df, by = "SampleID")
plot_df$Depth <- depth

p3 <- ggplot(plot_df, aes(x = group_prefix, y = Shannon, fill = group_prefix)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.15, outlier.shape = NA) +
  stat_compare_means(
    method = "wilcox.test",
    label.y = max(plot_df$Shannon) * 1.05,
    size = 6,
    fontface = "bold"
  ) +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = "Chao1 Index") +
  scale_fill_manual(values = c("LTS" = "#E69F00", "STS" = "#56B4E9")) +
  theme(
    legend.position = "none",
    axis.title.y = element_text(face = "bold", size = 18),
    axis.text = element_text(face = "bold", size = 14),
    axis.title.x = element_blank(),
    plot.title = element_blank()
  )

ggsave("tumer_chao1_violin.eps", plot = p3, device = cairo_ps, width = 6, height = 5)
p3
```

```{r}
pp = ggplot(plot_df, aes(x = group_prefix, y = Shannon, fill = group_prefix)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.15, outlier.shape = NA) +
  stat_deshape_compare(
    confounder_data = plot_df,
    confounder = c("Cohort", "Depth"),
    alternative = "greater",
    label.y = max(plot_df$Shannon) * 0.94,label.x = 0.5,
    size = 6,
    fontface = "bold"
  ) +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = "Chao1 Index") +
  scale_fill_manual(values = c("LTS" = "#E69F00", "STS" = "#56B4E9")) +
  theme(
    legend.position = "none",
    axis.title.y = element_text(face = "bold", size = 18),
    axis.text = element_text(face = "bold", size = 14),
    axis.title.x = element_blank(),
    plot.title = element_blank()
  )

ggsave("Tumour_chao1_deshape.eps", plot = pp, device = cairo_ps, width = 6, height = 5)
```

```{r}
### Permutation-based test

### DeSHAPE 1: Median Diff Test
deshape_perm_pair(Shannon ~ group_prefix,
               data        = plot_df,
               mode        = "center",     # or "dispersion", "skewness
               alternative = "greater",
               perm        = 10000,
               seed = 2025)


### DeSHAPE 2: Dispersion Diff Test
deshape_perm_pair(Shannon ~ group_prefix,
               data        = plot_df,
               mode        = "dispersion",     # or "dispersion", "skewness"
               alternative = "greater",
               perm        = 10000,
               seed = 2025)

### DeSHAPE 3: Asymmetry Test
deshape_perm_pair(Shannon ~ group_prefix,
               data        = plot_df,
               mode        = "skewness",     # or "dispersion", "skewness"
               alternative = "greater",
               perm        = 10000,
               seed = 2025)
```

```{r}
### DeSHAPE 1: Median Diff via Quantile Reg
qr_fit <- rq(Shannon ~ group_prefix,
             data = plot_df,
             tau = 0.5,
             method = "fn")

set.seed(2025)
summary(qr_fit, se = "boot") 

# adjust sequencing depth
qr_fit_d <- rq(Shannon ~ group_prefix + Depth,
               data = plot_df,
               tau = 0.5,
               method = "fn")

set.seed(2025)
summary(qr_fit_d, se = "boot") 

# adjust sequencing depth and other confounders
qr_fit_d_c <- rq(Shannon ~ group_prefix + Cohort + Depth,
               data = plot_df,
               tau = 0.5,
               method = "fn")

set.seed(2025)
summary(qr_fit_d_c, se = "boot") 

### DeSHAPE 2: Dispersion Diff via Quantile Reg
deshape_wald_contrast(Shannon ~ group_prefix,
                   data = plot_df,
                   taus = c(0.25,0.75),
                   contrast = c(0,-1,0,1),
                   alternative = "greater",
                   kernel = "gaussian")

# adjust sequencing depth
deshape_wald_contrast(Shannon ~ group_prefix + Depth,
                   data = plot_df,
                   taus = c(0.25,0.75),
                   contrast = c(0,-1,0,0,1,0),
                   alternative = "greater",
                   kernel = "gaussian")

# adjust sequencing depth and other confounders
deshape_wald_contrast(Shannon ~ group_prefix + Cohort + Depth,
                   data = plot_df,
                   taus = c(0.25,0.75),
                   contrast = c(0,-1,0,0,0,1,0,0),
                   alternative = "greater",
                   kernel = "gaussian")

### DeSHAPE 3: Asymmetry Diff via Quantile Reg
deshape_wald_contrast(Shannon ~ group_prefix,
                   data = plot_df,
                   taus = c(0.1,0.5,0.9),
                   contrast = c(0,1,0,-2,0,1),
                   alternative = "greater",
                   kernel = "gaussian")

# adjust sequencing depth
deshape_wald_contrast(Shannon ~ group_prefix + Depth,
                   data = plot_df,
                   taus = c(0.1,0.5,0.9),
                   contrast = c(0,1,0,0,-2,0,0,1,0),
                   alternative = "greater",
                   kernel = "gaussian")

# adjust sequencing depth and other confounders
deshape_wald_contrast(Shannon ~ group_prefix + Cohort + Depth,
                   data = plot_df,
                   taus = c(0.1,0.5,0.9),
                   contrast = c(0,1,0,0,0,-2,0,0,0,1,0,0),
                   alternative = "greater",
                   kernel = "gaussian")

```

```{r}
deshape_glm_resid_test(Shannon ~ group_prefix + Cohort + Depth,
                       data = plot_df,
                       mode = "center",
                       family = Gamma(link = "log"), 
                       group = "group_prefix",  # grouping variable name
                       alternative = "greater",
                       q = 0.25, B = 999, seed = 2025)$p.value

deshape_glm_resid_test(Shannon ~ group_prefix + Cohort + Depth,
                       data = plot_df,
                       mode = "dispersion",
                       family = Gamma(link = "log"), 
                       group = "group_prefix",  # grouping variable name
                       alternative = "greater",
                       q = 0.25, B = 999, seed = 2025)$p.value

deshape_glm_resid_test(Shannon ~ group_prefix + Cohort + Depth,
                       data = plot_df,
                       mode = "skewness",
                       family = Gamma(link = "log"), 
                       group = "group_prefix",  # grouping variable name
                       alternative = "greater",
                       q = 0.1, B = 999, seed = 2025)$p.value
```

## q-PD (q=1)

```{r}
tree = phy_tree(phy_16S)
shannon_vec <-  hill_phylo(comm = otu_mat, tree = tree, q = 1, rel_then_pool = FALSE)

# Assign sample names
names(shannon_vec) <- rownames(otu_mat)
shannon_df <- data.frame(SampleID = rownames(otu_mat),
                         Shannon = shannon_vec)

meta_df <- as(sample_data(phy_16S),"data.frame")
meta_df$SampleID <- rownames(meta_df)

plot_df <- merge(shannon_df, meta_df, by = "SampleID")
plot_df$Depth <- depth

p4 <- ggplot(plot_df, aes(x = group_prefix, y = Shannon, fill = group_prefix)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.15, outlier.shape = NA) +
  stat_compare_means(
    method = "wilcox.test",
    label.y = max(plot_df$Shannon) * 1.05,
    size = 6,
    fontface = "bold"
  ) +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = "q-PD (q =1) Index") +
  scale_fill_manual(values = c("LTS" = "#E69F00", "STS" = "#56B4E9")) +
  theme(
    legend.position = "none",
    axis.title.y = element_text(face = "bold", size = 18),
    axis.text = element_text(face = "bold", size = 14),
    axis.title.x = element_blank(),
    plot.title = element_blank()
  )

ggsave("tumer_qPD_violin.eps", plot = p4, device = cairo_ps, width = 6, height = 5)
p4
```

```{r}
pp = ggplot(plot_df, aes(x = group_prefix, y = Shannon, fill = group_prefix)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.15, outlier.shape = NA) +
  stat_deshape_compare(
    confounder_data = plot_df,
    confounder = c("Cohort", "Depth"),
    alternative = "greater",
    label.y = max(plot_df$Shannon) * 0.95,label.x = 0.5,
    size = 6,
    fontface = "bold"
  ) +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = "q-PD (q =1) Index") +
  scale_fill_manual(values = c("LTS" = "#E69F00", "STS" = "#56B4E9")) +
  theme(
    legend.position = "none",
    axis.title.y = element_text(face = "bold", size = 18),
    axis.text = element_text(face = "bold", size = 14),
    axis.title.x = element_blank(),
    plot.title = element_blank()
  )

ggsave("Tumour_qPD_deshape.eps", plot = pp, device = cairo_ps, width = 6, height = 5)
```

```{r}
library(cowplot)
library(magick)
library(ggplot2)
grid <- plot_grid(p1, p2, p3, p4, ncol = 2, align = "hv")
ggsave("Tumour_combined_2x2.eps", grid, device = cairo_ps, width = 8, height = 8, units = "in")
```

```{r}
### Permutation-based test

### DeSHAPE 1: Median Diff Test
deshape_perm_pair(Shannon ~ group_prefix,
               data        = plot_df,
               mode        = "center",     # or "dispersion", "skewness
               alternative = "greater",
               perm        = 10000,
               seed = 2025)


### DeSHAPE 2: Dispersion Diff Test
deshape_perm_pair(Shannon ~ group_prefix,
               data        = plot_df,
               mode        = "dispersion",     # or "dispersion", "skewness"
               alternative = "greater",
               perm        = 10000,
               seed = 2025)

### DeSHAPE 3: Asymmetry Test
deshape_perm_pair(Shannon ~ group_prefix,
               data        = plot_df,
               mode        = "skewness",     # or "dispersion", "skewness"
               alternative = "greater",
               perm        = 10000,
               seed = 2025)
```


```{r}
### DeSHAPE 1: Median Diff via Quantile Reg
qr_fit <- rq(Shannon ~ group_prefix,
             data = plot_df,
             tau = 0.5,
             method = "fn")

set.seed(2025)
summary(qr_fit, se = "boot") 

# adjust sequencing depth
qr_fit_d <- rq(Shannon ~ group_prefix + Depth,
               data = plot_df,
               tau = 0.5,
               method = "fn")

set.seed(2025)
summary(qr_fit_d, se = "boot") 

# adjust sequencing depth and other confounders
qr_fit_d_c <- rq(Shannon ~ group_prefix + Cohort + Depth,
               data = plot_df,
               tau = 0.5,
               method = "fn")

set.seed(2025)
summary(qr_fit_d_c, se = "boot") 

### DeSHAPE 2: Dispersion Diff via Quantile Reg
deshape_wald_contrast(Shannon ~ group_prefix,
                   data = plot_df,
                   taus = c(0.25,0.75),
                   contrast = c(0,-1,0,1),
                   alternative = "greater",
                   kernel = "gaussian")

# adjust sequencing depth
deshape_wald_contrast(Shannon ~ group_prefix + Depth,
                   data = plot_df,
                   taus = c(0.25,0.75),
                   contrast = c(0,-1,0,0,1,0),
                   alternative = "greater",
                   kernel = "gaussian")

# adjust sequencing depth and other confounders
deshape_wald_contrast(Shannon ~ group_prefix + Cohort + Depth,
                   data = plot_df,
                   taus = c(0.25,0.75),
                   contrast = c(0,-1,0,0,0,1,0,0),
                   alternative = "greater",
                   kernel = "gaussian")

### DeSHAPE 3: Asymmetry Diff via Quantile Reg
deshape_wald_contrast(Shannon ~ group_prefix,
                   data = plot_df,
                   taus = c(0.1,0.5,0.9),
                   contrast = c(0,1,0,-2,0,1),
                   alternative = "greater",
                   kernel = "gaussian")

# adjust sequencing depth
deshape_wald_contrast(Shannon ~ group_prefix + Depth,
                   data = plot_df,
                   taus = c(0.1,0.5,0.9),
                   contrast = c(0,1,0,0,-2,0,0,1,0),
                   alternative = "greater",
                   kernel = "gaussian")

# adjust sequencing depth and other confounders
deshape_wald_contrast(Shannon ~ group_prefix + Cohort + Depth,
                   data = plot_df,
                   taus = c(0.1,0.5,0.9),
                   contrast = c(0,1,0,0,0,-2,0,0,0,1,0,0),
                   alternative = "greater",
                   kernel = "gaussian")

```

```{r}
deshape_glm_resid_test(Shannon ~ group_prefix + Cohort + Depth,
                       data = plot_df,
                       mode = "center",
                       family = Gamma(link = "log"), 
                       group = "group_prefix",  # grouping variable name
                       alternative = "greater",
                       q = 0.25, B = 999, seed = 2025)$p.value

deshape_glm_resid_test(Shannon ~ group_prefix + Cohort + Depth,
                       data = plot_df,
                       mode = "dispersion",
                       family = Gamma(link = "log"), 
                       group = "group_prefix",  # grouping variable name
                       alternative = "greater",
                       q = 0.25, B = 999, seed = 2025)$p.value

deshape_glm_resid_test(Shannon ~ group_prefix + Cohort + Depth,
                       data = plot_df,
                       mode = "skewness",
                       family = Gamma(link = "log"), 
                       group = "group_prefix",  # grouping variable name
                       alternative = "greater",
                       q = 0.1, B = 999, seed = 2025)$p.value
```

# Hadza

```{r}
load("../Real_Data/hadza.RData")
```



```{r}
library(phyloseq)
library(dplyr)
## 1. Keep only 2014 seasons ---------------------------------------------

# subset samples whose season starts with "2014-"
physeq_2014 <- subset_samples(physeq, grepl("^2014-", season))

## 2. Create two new sample variables: Late/Early and Wet/Dry ------------

# pull sample_data into a data.frame
meta <- as(sample_data(physeq_2014), "data.frame")

# remove the "2014-" prefix, leaving "LW", "EW", "LD", "ED", etc.
season_code <- sub("^2014-", "", meta$season)

# first letter: L/E  → Late/Early
phase_code <- substr(season_code, 1, 1)

# second letter: W/D → Wet/Dry
wetdry_code <- substr(season_code, 2, 2)

meta$season_phase <- factor(
  ifelse(phase_code == "L", "Late",
         ifelse(phase_code == "E", "Early", NA)),
  levels = c("Early", "Late")
)

meta$season_wetdry <- factor(
  ifelse(wetdry_code == "W", "Wet",
         ifelse(wetdry_code == "D", "Dry", NA)),
  levels = c("Dry", "Wet")
)

```

## Shannon

```{r}
otu_mat = otu_table(physeq_2014)
if (taxa_are_rows(physeq_2014)) {
  otu_mat <- t(otu_mat)
}
shannon_vec <- diversity(otu_mat, index = "shannon")
shannon_df <- data.frame(SampleID = rownames(otu_mat),
                         Shannon = shannon_vec)


if (!"SampleID" %in% colnames(meta)) {
  meta$SampleID <- rownames(meta)
}
plot_df <- merge(shannon_df, meta, by = "SampleID")



p1 <- ggplot(plot_df, aes(x = season_wetdry, y = Shannon, fill = season_wetdry)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.15, outlier.shape = NA) +
  stat_compare_means(method = "wilcox.test",
                     label.y  = max(plot_df$Shannon) * 1.05,
                     size     = 5.5,
                     fontface = "bold") +
  scale_fill_manual(values = c("Wet"  = "#56B4E9",
                               "Dry" = "#E69F00")) +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = "Shannon Index") +
  theme(legend.position = "none",
        axis.title.y    = element_text(face = "bold", size = 18),
        axis.text       = element_text(face = "bold", size = 14),
        plot.title      = element_blank())

ggsave("hadza_shannon_violin.eps", plot = p1, device = cairo_ps, width = 6, height = 5)
p1

```


```{r}
pp = ggplot(plot_df, aes(x = season_wetdry, y = Shannon, fill = season_wetdry)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.15, outlier.shape = NA) +
  stat_deshape_compare(
    confounder_data = plot_df,
    confounder = c("season_phase"),
    alternative = "two.sided",
    label.y = max(plot_df$Shannon) * 0.90,label.x = 0.5,
    size = 6,
    fontface = "bold"
  ) +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = "Shannon Index") +
  scale_fill_manual(values = c("Dry" = "#E69F00", "Wet" = "#56B4E9")) +
  theme(
    legend.position = "none",
    axis.title.y = element_text(face = "bold", size = 18),
    axis.text = element_text(face = "bold", size = 14),
    axis.title.x = element_blank(),
    plot.title = element_blank()
  )

ggsave("Hadza_Shannon_deshape.eps", plot = pp, device = cairo_ps, width = 6, height = 5)
```


```{r}
### Permutation-based test

### DeSHAPE 1: Median Diff Test
deshape_perm_pair(Shannon ~ season_wetdry,
               data        = plot_df,
               mode        = "center",     # or "dispersion", "skewness
               alternative = "two.sided",
               perm        = 10000,
               seed = 2025)


### DeSHAPE 2: Dispersion Diff Test
deshape_perm_pair(Shannon ~ season_wetdry,
               data        = plot_df,
               mode        = "dispersion",     # or "dispersion", "skewness"
               alternative = "two.sided",
               perm        = 10000,
               seed = 2025)

### DeSHAPE 3: Asymmetry Test
deshape_perm_pair(Shannon ~ season_wetdry,
               data        = plot_df,
               mode        = "skewness",     # or "dispersion", "skewness"
               alternative = "two.sided",
               perm        = 10000,
               seed = 2025)
```

```{r}
### DeSHAPE 1: Median Diff via Quantile Reg
qr_fit <- rq(Shannon ~ season_wetdry,
             data = plot_df,
             tau = 0.5,
             method = "fn")

set.seed(2025)
summary(qr_fit, se = "boot") 

# adjust sequencing depth
qr_fit_d <- rq(Shannon ~ season_wetdry + season_phase,
               data = plot_df,
               tau = 0.5,
               method = "fn")

set.seed(2025)
summary(qr_fit_d, se = "boot") 



### DeSHAPE 2: Dispersion Diff via Quantile Reg
deshape_wald_contrast(Shannon ~ season_wetdry,
                   data = plot_df,
                   mode = "dispersion",
                   alternative = "two.sided",
                   kernel = "gaussian")

# adjust sequencing depth
deshape_wald_contrast(Shannon ~ season_wetdry + season_phase,
                   data = plot_df,
                   mode = "dispersion",
                   alternative = "two.sided",
                   kernel = "gaussian")



### DeSHAPE 3: Asymmetry Diff via Quantile Reg
deshape_wald_contrast(Shannon ~ season_wetdry,
                   data = plot_df,
                   mode = "symmetry",
                   alternative = "two.sided",
                   kernel = "gaussian")

# adjust sequencing depth
deshape_wald_contrast(Shannon ~ season_wetdry + season_phase,
                   data = plot_df,
                   mode = "symmetry",
                   alternative = "two.sided",
                   kernel = "gaussian")



```


## Faith's PD

```{r}
otu_mat = otu_table(physeq_2014)
if (taxa_are_rows(physeq_2014)) {
  otu_mat <- t(otu_mat)
}

shannon_df <- data.frame(SampleID = rownames(otu_mat),
                         Shannon = meta$PD_whole_tree)


if (!"SampleID" %in% colnames(meta)) {
  meta$SampleID <- rownames(meta)
}
plot_df <- merge(shannon_df, meta, by = "SampleID")



p2 <- ggplot(plot_df, aes(x = season_wetdry, y = Shannon, fill = season_wetdry)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.15, outlier.shape = NA) +
  stat_compare_means(method = "wilcox.test",
                     label.y  = max(plot_df$Shannon) * 1.05,
                     size     = 5.5,
                     fontface = "bold") +
  scale_fill_manual(values = c("Wet"  = "#56B4E9",
                               "Dry" = "#E69F00")) +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = "Faith's PD Index") +
  theme(legend.position = "none",
        axis.title.y    = element_text(face = "bold", size = 18),
        axis.text       = element_text(face = "bold", size = 14),
        plot.title      = element_blank())

ggsave("hadza_FaithPD_violin.eps", plot = p2, device = cairo_ps, width = 6, height = 5)
p2

```

```{r}
pp = ggplot(plot_df, aes(x = season_wetdry, y = Shannon, fill = season_wetdry)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.15, outlier.shape = NA) +
  stat_deshape_compare(
    confounder_data = plot_df,
    confounder = c("season_phase"),
    alternative = "two.sided",
    label.y = max(plot_df$Shannon) * 0.90,label.x = 0.5,
    size = 6,
    fontface = "bold"
  ) +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = "Faith's PD Index") +
  scale_fill_manual(values = c("Dry" = "#E69F00", "Wet" = "#56B4E9")) +
  theme(
    legend.position = "none",
    axis.title.y = element_text(face = "bold", size = 18),
    axis.text = element_text(face = "bold", size = 14),
    axis.title.x = element_blank(),
    plot.title = element_blank()
  )

ggsave("Hadza_FaithsPD_deshape.eps", plot = pp, device = cairo_ps, width = 6, height = 5)
```


```{r}
### Permutation-based test

### DeSHAPE 1: Median Diff Test
deshape_perm_pair(Shannon ~ season_wetdry,
               data        = plot_df,
               mode        = "center",     # or "dispersion", "skewness
               alternative = "two.sided",
               perm        = 10000,
               seed = 2025)


### DeSHAPE 2: Dispersion Diff Test
deshape_perm_pair(Shannon ~ season_wetdry,
               data        = plot_df,
               mode        = "dispersion",     # or "dispersion", "skewness"
               alternative = "two.sided",
               perm        = 10000,
               seed = 2025)

### DeSHAPE 3: Asymmetry Test
deshape_perm_pair(Shannon ~ season_wetdry,
               data        = plot_df,
               mode        = "skewness",     # or "dispersion", "skewness"
               alternative = "two.sided",
               perm        = 10000,
               seed = 2025)
```

```{r}
### DeSHAPE 1: Median Diff via Quantile Reg
qr_fit <- rq(Shannon ~ season_wetdry,
             data = plot_df,
             tau = 0.5,
             method = "fn")

set.seed(2025)
summary(qr_fit, se = "boot") 

# adjust sequencing depth
qr_fit_d <- rq(Shannon ~ season_wetdry + season_phase,
               data = plot_df,
               tau = 0.5,
               method = "fn")

set.seed(2025)
summary(qr_fit_d, se = "boot") 



### DeSHAPE 2: Dispersion Diff via Quantile Reg
deshape_wald_contrast(Shannon ~ season_wetdry,
                   data = plot_df,
                   mode = "dispersion",
                   alternative = "two.sided",
                   kernel = "gaussian")

# adjust sequencing depth
deshape_wald_contrast(Shannon ~ season_wetdry + season_phase,
                   data = plot_df,
                   mode = "dispersion",
                   alternative = "two.sided",
                   kernel = "gaussian")



### DeSHAPE 3: Asymmetry Diff via Quantile Reg
deshape_wald_contrast(Shannon ~ season_wetdry,
                   data = plot_df,
                   mode = "symmetry",
                   alternative = "two.sided",
                   kernel = "gaussian")

# adjust sequencing depth
deshape_wald_contrast(Shannon ~ season_wetdry + season_phase,
                   data = plot_df,
                   mode = "symmetry",
                   alternative = "two.sided",
                   kernel = "gaussian")



```

## Richness

```{r}
otu_mat = otu_table(physeq_2014)
if (taxa_are_rows(physeq_2014)) {
  otu_mat <- t(otu_mat)
}
shannon_vec <- rowSums(otu_mat > 0)
shannon_df <- data.frame(SampleID = rownames(otu_mat),
                         Shannon = shannon_vec)


if (!"SampleID" %in% colnames(meta)) {
  meta$SampleID <- rownames(meta)
}
plot_df <- merge(shannon_df, meta, by = "SampleID")



p3 <- ggplot(plot_df, aes(x = season_wetdry, y = Shannon, fill = season_wetdry)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.15, outlier.shape = NA) +
  stat_compare_means(method = "wilcox.test",
                     label.y  = max(plot_df$Shannon) * 1.05,
                     size     = 5.5,
                     fontface = "bold") +
  scale_fill_manual(values = c("Wet"  = "#56B4E9",
                               "Dry" = "#E69F00")) +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = "Richness Index") +
  theme(legend.position = "none",
        axis.title.y    = element_text(face = "bold", size = 18),
        axis.text       = element_text(face = "bold", size = 14),
        plot.title      = element_blank())

ggsave("hadza_richness_violin.eps", plot = p3, device = cairo_ps, width = 6, height = 5)
p3

```

```{r}
pp = ggplot(plot_df, aes(x = season_wetdry, y = Shannon, fill = season_wetdry)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.15, outlier.shape = NA) +
  stat_deshape_compare(
    confounder_data = plot_df,
    confounder = c("season_phase"),
    alternative = "two.sided",
    label.y = max(plot_df$Shannon) * 0.90,label.x = 0.5,
    size = 6,
    fontface = "bold"
  ) +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = "Richness Index") +
  scale_fill_manual(values = c("Dry" = "#E69F00", "Wet" = "#56B4E9")) +
  theme(
    legend.position = "none",
    axis.title.y = element_text(face = "bold", size = 18),
    axis.text = element_text(face = "bold", size = 14),
    axis.title.x = element_blank(),
    plot.title = element_blank()
  )

ggsave("Hadza_Richness_deshape.eps", plot = pp, device = cairo_ps, width = 6, height = 5)
```

```{r}
### Permutation-based test

### DeSHAPE 1: Median Diff Test
deshape_perm_pair(Shannon ~ season_wetdry,
               data        = plot_df,
               mode        = "center",     # or "dispersion", "skewness
               alternative = "two.sided",
               perm        = 10000,
               seed = 2025)


### DeSHAPE 2: Dispersion Diff Test
deshape_perm_pair(Shannon ~ season_wetdry,
               data        = plot_df,
               mode        = "dispersion",     # or "dispersion", "skewness"
               alternative = "two.sided",
               perm        = 10000,
               seed = 2025)

### DeSHAPE 3: Asymmetry Test
deshape_perm_pair(Shannon ~ season_wetdry,
               data        = plot_df,
               mode        = "skewness",     # or "dispersion", "skewness"
               alternative = "two.sided",
               perm        = 10000,
               seed = 2025)
```


```{r}
### DeSHAPE 1: Median Diff via Quantile Reg
qr_fit <- rq(Shannon ~ season_wetdry,
             data = plot_df,
             tau = 0.5,
             method = "fn")

set.seed(2025)
summary(qr_fit, se = "boot") 

# adjust sequencing depth
qr_fit_d <- rq(Shannon ~ season_wetdry + season_phase,
               data = plot_df,
               tau = 0.5,
               method = "fn")

set.seed(2025)
summary(qr_fit_d, se = "boot") 



### DeSHAPE 2: Dispersion Diff via Quantile Reg
deshape_wald_contrast(Shannon ~ season_wetdry,
                   data = plot_df,
                   mode = "dispersion",
                   alternative = "two.sided",
                   kernel = "gaussian")

# adjust sequencing depth
deshape_wald_contrast(Shannon ~ season_wetdry + season_phase,
                   data = plot_df,
                   mode = "dispersion",
                   alternative = "two.sided",
                   kernel = "gaussian")



### DeSHAPE 3: Asymmetry Diff via Quantile Reg
deshape_wald_contrast(Shannon ~ season_wetdry,
                   data = plot_df,
                   mode = "symmetry",
                   alternative = "two.sided",
                   kernel = "gaussian")

# adjust sequencing depth
deshape_wald_contrast(Shannon ~ season_wetdry + season_phase,
                   data = plot_df,
                   mode = "symmetry",
                   alternative = "two.sided",
                   kernel = "gaussian")



```

## q-PD(q = 1)

```{r}
otu_mat = otu_table(physeq_2014)
if (taxa_are_rows(physeq_2014)) {
  otu_mat <- t(otu_mat)
}
tree = phy_tree(physeq_2014)
shannon_vec <-  hill_phylo(comm = otu_mat, tree = tree, q = 1, rel_then_pool = FALSE)

shannon_df <- data.frame(SampleID = rownames(otu_mat),
                         Shannon = shannon_vec)


if (!"SampleID" %in% colnames(meta)) {
  meta$SampleID <- rownames(meta)
}
plot_df <- merge(shannon_df, meta, by = "SampleID")



p4 <- ggplot(plot_df, aes(x = season_wetdry, y = Shannon, fill = season_wetdry)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.15, outlier.shape = NA) +
  stat_compare_means(method = "wilcox.test",
                     label.y  = max(plot_df$Shannon) * 1.05,
                     size     = 5.5,
                     fontface = "bold") +
  scale_fill_manual(values = c("Wet"  = "#56B4E9",
                               "Dry" = "#E69F00")) +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = "q-PD (q = 1) Index") +
  theme(legend.position = "none",
        axis.title.y    = element_text(face = "bold", size = 18),
        axis.text       = element_text(face = "bold", size = 14),
        plot.title      = element_blank())

ggsave("hadza_qpd_violin.eps", plot = p4, device = cairo_ps, width = 6, height = 5)
p4

```


```{r}
pp = ggplot(plot_df, aes(x = season_wetdry, y = Shannon, fill = season_wetdry)) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.15, outlier.shape = NA) +
  stat_deshape_compare(
    confounder_data = plot_df,
    confounder = c("season_phase"),
    alternative = "two.sided",
    label.y = max(plot_df$Shannon) * 0.90,label.x = 0.5,
    size = 6,
    fontface = "bold"
  ) +
  theme_minimal(base_size = 14) +
  labs(x = NULL, y = "q-PD (q = 1) Index") +
  scale_fill_manual(values = c("Dry" = "#E69F00", "Wet" = "#56B4E9")) +
  theme(
    legend.position = "none",
    axis.title.y = element_text(face = "bold", size = 18),
    axis.text = element_text(face = "bold", size = 14),
    axis.title.x = element_blank(),
    plot.title = element_blank()
  )

ggsave("Hadza_qPD_deshape.eps", plot = pp, device = cairo_ps, width = 6, height = 5)
```

```{r}
### Permutation-based test

### DeSHAPE 1: Median Diff Test
deshape_perm_pair(Shannon ~ season_wetdry,
               data        = plot_df,
               mode        = "center",     # or "dispersion", "skewness
               alternative = "two.sided",
               perm        = 10000,
               seed = 2025)


### DeSHAPE 2: Dispersion Diff Test
deshape_perm_pair(Shannon ~ season_wetdry,
               data        = plot_df,
               mode        = "dispersion",     # or "dispersion", "skewness"
               alternative = "two.sided",
               perm        = 10000,
               seed = 2025)

### DeSHAPE 3: Asymmetry Test
deshape_perm_pair(Shannon ~ season_wetdry,
               data        = plot_df,
               mode        = "skewness",     # or "dispersion", "skewness"
               alternative = "two.sided",
               perm        = 10000,
               seed = 2025)
```

```{r}
### DeSHAPE 1: Median Diff via Quantile Reg
qr_fit <- rq(Shannon ~ season_wetdry,
             data = plot_df,
             tau = 0.5,
             method = "fn")

set.seed(2025)
summary(qr_fit, se = "boot") 

# adjust sequencing depth
qr_fit_d <- rq(Shannon ~ season_wetdry + season_phase,
               data = plot_df,
               tau = 0.5,
               method = "fn")

set.seed(2025)
summary(qr_fit_d, se = "boot") 



### DeSHAPE 2: Dispersion Diff via Quantile Reg
deshape_wald_contrast(Shannon ~ season_wetdry,
                   data = plot_df,
                   mode = "dispersion",
                   alternative = "two.sided",
                   kernel = "gaussian")

# adjust sequencing depth
deshape_wald_contrast(Shannon ~ season_wetdry + season_phase,
                   data = plot_df,
                   mode = "dispersion",
                   alternative = "two.sided",
                   kernel = "gaussian")



### DeSHAPE 3: Asymmetry Diff via Quantile Reg
deshape_wald_contrast(Shannon ~ season_wetdry,
                   data = plot_df,
                   mode = "symmetry",
                   alternative = "two.sided",
                   kernel = "gaussian")

# adjust sequencing depth
deshape_wald_contrast(Shannon ~ season_wetdry + season_phase,
                   data = plot_df,
                   mode = "symmetry",
                   alternative = "two.sided",
                   kernel = "gaussian")



```


```{r}
library(cowplot)
library(magick)
library(ggplot2)
grid <- plot_grid(p1, p2, p3, p4, ncol = 2, align = "hv")
ggsave("Hadza_combined_2x2.eps", grid, device = cairo_ps, width = 8, height = 8, units = "in")
```

